### ISSUE TITLE
Mention 'frame-ancestors' CSP rule with X-Frame-Options header

### ISSUE THREAD

**Issue by peksapro** [OWASP/www-project-secure-headers#10]
Hi guys.
Maybe it would be worth mentioning the 'frame-ancestors' CSP rule in the X-Frame-Options section.
Due to https://www.w3.org/TR/CSP11/#frame-ancestors-and-frame-options
What do you think?

**Comment by riramar** [comment]
Thanks! Updated through 6295cd4.
Please feel free to send PRs. :)
