### ISSUE TITLE
About "Technical References Dashboard"

### ISSUE THREAD

**Issue by rfc-st** [OWASP/www-project-secure-headers#102]
Hello,

Regarding the _Technical References Dashboard_ (https://github.com/OWASP/www-project-secure-headers/blob/master/monitoring_technical_references_dashboard.md): when and how do you update it?

The latest version of my tool (https://github.com/rfc-st/humble/) appears on that page dated **2022-09-05**, but just today I made several changes; and generated a new release two weeks ago.

Thanks.

**Comment by righettod** [comment]
Hello,

Thanks for raising the bug 😃 

The MD file of the dashboard is generated by this [workflow](https://github.com/OWASP/www-project-secure-headers/blob/master/.github/workflows/monitoring-technical-references-generate-dashboard.yml) every time the file **tab_technical.md** is modified.

Last time was:

![image](https://user-images.githubusercontent.com/1573775/197378954-685a2c91-5854-421a-ab2e-ed00105b3e42.png)

I checked manually the update date of your repo:

![image](https://user-images.githubusercontent.com/1573775/197379055-b4b6b8f1-d860-4062-b906-7a8ea160a5c0.png)

API was returning `2022-10-22T16:16:50Z` that fit the date you mentioned.

I will add a scheduling to the workflow in addition to the modification of the **tab_technical.md** to ensure that the dashboard is in sync every week.

**Comment by righettod** [comment]
PR #103 submitted to fix the issue 😃

**Comment by righettod** [comment]
Fixed by the PR
