### ISSUE TITLE
About "Technical References Dashboard" updates (again) :)

### ISSUE THREAD

**Issue by rfc-st** [OWASP/www-project-secure-headers#129]
Sorry if I don't understand well how https://github.com/OWASP/www-project-secure-headers/blob/master/monitoring_technical_references_dashboard.md updates works, but in my specific case (https://github.com/rfc-st/humble/) the panel indicates that my repository has not been updated for two months, when two weeks ago I published my last release and every weekend there are new commits (the last one twenty minutes ago!).

Thank you!

**Comment by righettod** [comment]
Hi, I will investigate on this and get back to you ASAP. Thanks again for
the notification about the bug. Have a great weekend.

**Comment by righettod** [comment]
I identified the bug 👀 

In [this script](https://github.com/OWASP/www-project-secure-headers/blob/master/ci/monitoring_technical_references_generate_dashboard.py#L72),  I am taking the attribute `updated_at` and instead I should take the `pushed_at` attribute that is more accurate regarding the repository *last updated* date time:

![image](https://user-images.githubusercontent.com/1573775/219609742-180c98b9-822b-4729-87eb-f4661642cf99.png)

I will fix that 👍 

Thanks again @rfc-st for the bug report 🥇

**Comment by righettod** [comment]
PR #130 submitted

**Comment by rfc-st** [comment]
Nice, thanks!.
