### ISSUE TITLE
Have an idea to include how to do API-Security using this project

### ISSUE THREAD

**Issue by AmitKulkarni9** [OWASP/www-project-secure-headers#16]
I am keen to contribute to this project. I have created below repository on how to do API-Security using OWASP Secure Headers Project. This is created using Python. This can be included here as an example or use-case. Please go over below repository and let me know your thoughts. 

https://github.com/AmitKulkarni9/API-Security

Thanks,
Amit Kulkarni

**Comment by riramar** [comment]
Can you send a PR to include your project under Technical Resources tab?

**Comment by AmitKulkarni9** [comment]
Created Below PR
https://github.com/OWASP/www-project-secure-headers/pull/21

**Comment by AmitKulkarni9** [comment]
Created below PR to include under Technical Resources tab
https://github.com/OWASP/www-project-secure-headers/pull/22

**Comment by riramar** [comment]
Hi @AmitKulkarni9 

You forgot to include the title using the same standard notation.
To make this easy I just included for your.
Thanks for your contribuition!

Regards
Ricardo Iramar
