### ISSUE TITLE
Idea proposal

### ISSUE THREAD

**Issue by righettod** [OWASP/www-project-secure-headers#20]
Hi,

In order to allow dev/infra teams to monitor or check the configuration of the headers on a site, I have created a quick "test suites" based on the tools [VENOM](https://github.com/ovh/venom) and the OSHP.

# Why VENOM?

It does not need any installation, you grab a release and run the test suite wanted. To customise the test suites, you only edit the YAML file with your context so you do not need to have coding skills to adapt the suites.

It allows to generate reports in different formats like JUNIT for example that can be easily integrated in a CI/CD pipeline.

# My proposal

OSHP can provide a base test suites (just a maintained YAML file) aligned with  the recommendations on the site. The goal is to allow OSHP users to quickly set up verification of the application of the recommendation proposed and easily customise the test suites in case of need. As the tool provide release for different OS as a single file, the proposed test suites do not require any extra installation or dependencies.

# The tests suite

[Test suites as a Gist](https://gist.github.com/righettod/f63548ebd96bed82269dcc3dfea27056).

It is just a proposal, feel free to send it to the trash if it does not goes into the way the project want to go 😃 

Thanks a lot in advance 😃

**Comment by riramar** [comment]
Can you send a PR to include your VENOM test suites under the Technical Resources tab?

**Comment by righettod** [comment]
Thank a lot, I will do it in coming days, you can assign me this issue

**Comment by righettod** [comment]
I will work on it this coming week-end.

**Comment by righettod** [comment]
PR #23 submitted 😃

**Comment by riramar** [comment]
Done!
