### ISSUE TITLE
[BUG] Official Logo Page Design

### ISSUE THREAD

**Issue by riramar** [OWASP/www-project-secure-headers#204]
It seems odd the official logo page design. Is that right?

![image](https://github.com/user-attachments/assets/1dd901bc-4461-447e-ad1e-f67084c991d2)

**Comment by righettod** [comment]
PR #205 submitted to address this issue and unify the rendering

**Comment by righettod** [comment]
PR #206 submitted to fix the error of the PR #203

**Comment by riramar** [comment]
Thanks!

**Comment by righettod** [comment]
I made a mistake with the folder reference. I will fix with a new PR 😅

**Comment by righettod** [comment]
PR #207 submitted to fix the ref error.

**Comment by riramar** [comment]
Thanks!
