### ISSUE TITLE
X-Frame-Options Obsolete

### ISSUE THREAD

**Issue by anthnyajp** [OWASP/www-project-secure-headers#35]
Per Mozilla, X-Frame-Options header is obsolete. Should not be a required header. See:  [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options](url)

**Comment by riramar** [comment]
Please send a PR with your proposal. Keep in mind there is a intention of replace XFO with CSP but right now XFO is simple and works fine to avoid clickjacking attacks and CSP is quite complicated.
