### ISSUE TITLE
Add the "Permissions Policy" http response header

### ISSUE THREAD

**Issue by righettod** [OWASP/www-project-secure-headers#37]
RFC:
- https://www.w3.org/TR/permissions-policy-1/

Documentation:
- https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md

Support:
- https://caniuse.com/permissions-policy
- https://www.chromestatus.com/feature/5745992911552512

This issue can be assigned to me if you are ok with this add 😃

**Comment by riramar** [comment]
Sure. Please go ahead. Thanks!

**Comment by righettod** [comment]
PR submitted 😃

**Comment by righettod** [comment]
PR merged
