### ISSUE TITLE
Expect-CT deprecated

### ISSUE THREAD

**Issue by mmpx12** [OWASP/www-project-secure-headers#43]
> ⚠️ Warning: This header will likely become obsolete in June 2021

should it be move from "Almost deprecated" to "Deprecated" ?

**Comment by riramar** [comment]
Seems browsers are still accepting this header (https://caniuse.com/?search=Expect-CT).
Do you have any reference regarding the deprecated ones?

**Comment by mmpx12** [comment]
That was a question, not an affirmation .

**Comment by riramar** [comment]
No since some browsers are still accepting this header (https://caniuse.com/?search=Expect-CT).
