### ISSUE TITLE
Make Content-Security-Policy header more secure

### ISSUE THREAD

**Issue by ddadon10** [OWASP/www-project-secure-headers#44]
Currently, the Content-Security-Policy recommendation in this document is as follow:

`default-src 'self' data:; object-src 'none'; child-src 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content` 

Though, according to [Google's CSP Evaluator](https://csp-evaluator.withgoogle.com/), the `data:` scheme allows the execution of unsafe scripts and can be used to craft an XSS Attack. For example, an attacker could craft the following url `data:text/html,<script>alert('hi');</script>` 

Content-Security-Policy being *very* error prone, I don't know how easy it would be to come with a "general" recommendation. 

A solution in mind would be to do what Google's CSP evaluator does: Removing the `data:` scheme and put a warning on `self` about JSONP and Angular library.  

What do you think?

**Comment by riramar** [comment]
It makes sense to me. Let me bring @drighetto to this discussion because I think he was to one who created this page.

**Comment by riramar** [comment]
It makes sense to me. Let me bring @righettod to this discussion because I think he was to one who created this page.

**Comment by righettod** [comment]
Hi,
Thank a lot @ddadon10 for raising this warning, you are absolutely right.
Let's only open the main origin by default and let the user adapt it in case of need.
I made a PR ASAP to fix this 😃 
Thanks again 💯

**Comment by righettod** [comment]
PR #45 proposed.

**Comment by riramar** [comment]
Merged! Thanks both of you!
