### ISSUE TITLE
X-XSS-Protection Header Deprecation Security Issue

### ISSUE THREAD

**Issue by ongcyhub** [OWASP/www-project-secure-headers#47]
In the deprecation of X-XSS-Protection Header it states that it will being security issues to the client side without specifying details. Will it be possible to state why ?

Will there be an impact to the confidentiality and integrity data if some one still applies this header?

**Comment by riramar** [comment]
Have you check the references section? I think this reference https://portswigger.net/daily-swig/google-chromes-xss-auditor-goes-back-to-filter-mode answer you question.
