### ISSUE TITLE
Notes on Feature-Policy

### ISSUE THREAD

**Issue by Malvoz** [OWASP/www-project-secure-headers#5]
Just writing this down as a reminder since I don't really have time atm, or if someone want to take this on:

- Probably need to add more feature identifiers, see https://github.com/w3c/webappsec-feature-policy/blob/master/features.md
- The `vr` feature identifier is obsolete, and should be replaced with `xr-spatial-tracking`
- `vibrate` was never implemented anywhere, nor specced anywhere, so as such it is invalid

Additionally, probably want to track https://github.com/w3c/webappsec-feature-policy/issues/359 as the `Feature-Policy` HTTP header may be renamed in the future.

**Comment by riramar** [comment]
Make sense. Can you send a push request?

**Comment by Malvoz** [comment]
> Feature-Policy HTTP header may be renamed in the future.

Feature Policy is now split into 2 new HTTP headers:

[`Permissions-Policy`](https://w3c.github.io/webappsec-feature-policy/#permissions-policy-http-header-field) and [`Document-Policy`](https://w3c.github.io/webappsec-feature-policy/document-policy#document-policy-http-header).
