### ISSUE TITLE
COEP / COOP / CORP

### ISSUE THREAD

**Issue by Malvoz** [OWASP/www-project-secure-headers#6]
New headers to keep an eye out for:

- [`Cross-Origin-Embedder-Policy` (COEP)](https://wicg.github.io/cross-origin-embedder-policy/)
- [`Cross-Origin-Opener-Policy` (COOP)](https://gist.github.com/annevk/6f2dd8c79c77123f39797f6bdac43f3e)
- [`Cross-Origin-Resource-Policy` (CORP)](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header) ([MDN link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)))

See related articles from web.dev:
[Making your website "cross-origin isolated" using COOP and COEP](https://web.dev/coop-coep/) 
[Why you need "cross-origin isolated" for powerful features](https://web.dev/why-coop-coep/)

**Comment by riramar** [comment]
Can you send a push request adding them in the same format from the other headers?

**Comment by righettod** [comment]
Hi, 
Once my PR #18 is processed, I can work on this topic and propose the corresponding PR.
Are you OK with this? 
Thanks in advance 😃

**Comment by righettod** [comment]
OK in the interval, my PR was merged 👍 
So I start on this topic 😄

**Comment by righettod** [comment]
Proposed in PR #19 😃

**Comment by riramar** [comment]
PR approved! 👍

**Comment by righettod** [comment]
Thanks !!!!
