### ISSUE TITLE
Auto feeding from scans.io

### ISSUE THREAD

**Issue by righettod** [OWASP/www-project-secure-headers#62]
### Description

Create a parser to grab the headers from https://scans.io/ and populate the MySQL database.

### Additional resources

* https://scans.io/

**Comment by righettod** [comment]
I think that is not relevant anymore due to way in which stats were generated.

@riramar  What do you think?

**Comment by riramar** [comment]
Make sense. You can close this issue if you want.

**Comment by righettod** [comment]
OK thanks
