### ISSUE TITLE
Potentially remove `X-XSS-Protection`

### ISSUE THREAD

**Issue by Malvoz** [OWASP/www-project-secure-headers#7]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) on `X-XSS-Protection` (I added this information to MDN, but you can check the linked resources to confirm):

> Chrome has [removed their XSS Auditor](https://www.chromestatus.com/feature/5021976655560704)
> Firefox have not, and [will not implement `X-XSS-Protection`](https://bugzilla.mozilla.org/show_bug.cgi?id=528661)
> Edge have [retired their XSS filter](https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/)

In short, the header isn't useful in modern browsers. Consider removing?

**Comment by riramar** [comment]
We can add a note to keep the log of this header.
Can you send a push request?

**Comment by calabacito** [comment]
This has been discussed over https://github.com/OWASP/CheatSheetSeries/issues/376#issue-585128093
I think we have a huge gap sharing info between projects @ThunderSon :(

**Comment by riramar** [comment]
hi @calabacito 

Thanks for providing this discussion. I totally agree that we should be aligned between OWASP projects as much as we can.
Some time ago I was talking to @ThunderSon  to get help to update the OWASP Secure Headers Project. If you guys want to take a look and send some PRs I'm really happy to approve. :)
I hope you guys don't mind but I copy the same explanation from OWASP CheatSheetSeries and update OWASP Secure Headers Project.

**Comment by ThunderSon** [comment]
Glad we were of help, and thanks @calabacito for raising this!
