### ISSUE TITLE
Potentially remove `Expect-CT`

### ISSUE THREAD

**Issue by Malvoz** [OWASP/www-project-secure-headers#8]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT:

> The `Expect-CT` will likely become obsolete in June 2021. Since May 2018 new certificates are expected to support SCTs by default. Certificates before March 2018 were allowed to have a lifetime of 39 months, those will all be expired in June 2021.

I'm not sure where to look for the source information, but assuming the note is correct, there will be very little reason to use this header. Consider removing?

**Comment by riramar** [comment]
We can add a note to keep the log of this header.
Can you send a push request?
