### ISSUE TITLE
Remove `Public-Key-Pins` (HPKP)

### ISSUE THREAD

**Issue by Malvoz** [OWASP/www-project-secure-headers#9]
There's essentially no browser support for this header, see [MDN compat data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#Browser_compatibility). I think it's safe to say that developers shouldn't spend time on implementing public key pins.

**Comment by riramar** [comment]
We can add a note like described here https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#Deprecated in order to keep a log.
Can you send a push request?

> Deprecated
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
